### ISSUE TITLE
Fails to compile with bleeding edge repo 124.06.323

### ISSUE THREAD

**Issue by andrewray** [janestreet/async_js#6]
Unbound value Js.js_error_of_exn

**Comment by hhugo** [comment]
Please pin js_of_ocaml to the dev version `opam pin add js_of_ocaml --dev`

**Comment by andrewray** [comment]
That worked.  Thanks!
